"""Shared interfaces for agent-specific generated files."""

from typing import Protocol

from repo_guard.adapters.claude import ClaudeAdapter
from repo_guard.adapters.codex import CodexAdapter
from repo_guard.adapters.cursor import CursorAdapter
from repo_guard.models import AgentChoice, TemplateSpec


class AgentAdapter(Protocol):
    """Adapter that contributes generated files for one coding-agent surface."""

    def template_specs(self) -> tuple[TemplateSpec, ...]:
        """Return templates generated by this adapter."""
        ...


def adapters_for(agent: AgentChoice) -> tuple[AgentAdapter, ...]:
    """Return concrete adapters selected by a `repo-guard init` option."""
    if agent == "codex":
        return (CodexAdapter(),)
    if agent == "claude":
        return (ClaudeAdapter(),)
    if agent == "cursor":
        return (CursorAdapter(),)
    return (CodexAdapter(), ClaudeAdapter(), CursorAdapter())
